name: webapp
description: A website for Figma to Flutter code generator.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  js: any
  http_server: ^1.0.0 
  figma_to_flutter:
    path: ../src

dev_dependencies:
  build_runner: ^2.0.4 
  build_web_compilers: ^3.0.0
 