name: figma_to_flutter_generator
description: A build generator for converting Figma files to Flutter widgets.
authors:
- Aloïs Deniel <alois.deniel@outlook.com>
environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  analyzer: ^1.7.1
  analyzer_plugin: ^0.6.0
  build: ^2.0.2
  build_config: ^1.0.0
  built_collection: ^5.0.0
  figma_to_flutter: 

dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.0.4
  test: ^1.0.0

dependency_overrides:
  figma_to_flutter:
    path: ../src